apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter-1
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://raw.githubusercontent.com/sika-training-examples/2025-12-11_helm_repo_example/refs/heads/master
    chart: counter
    targetRevision: 0.3.1
    helm:
      valuesObject:
        host: counter-1.k8s2.sikademo.com