apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter-2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sika-training-examples/2025-12-10_counter_kubernetes_example
      path: .
    - repoURL: https://github.com/sika-training-examples/2025-12-10_counter_kubernetes_example
      path: ./rke2